### ISSUE TITLE
functionList.xml for markdown files

### ISSUE THREAD

**Issue by heckl** [nea/MarkdownViewerPlusPlus#117]
This is a feature request. It would be useful if the functionList.xml is created for markdown files. If headings is regarded as functions then it would be easy to navigate between them.

**Comment by MAPJe71** [comment]
See Notepad++ GitHub issue [5945](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/5945) and Community topic [18458](https://community.notepad-plus-plus.org/topic/18458/display-markdown-outline-view-through-functionlist).
