### ISSUE TITLE
Incompatible with Dark Themes / Night Mode?

### ISSUE THREAD

**Issue by WandersFar** [nea/MarkdownViewerPlusPlus#126]
I recently switched to a dark theme on my system (W10) and while Notepad++ itself adjusted gracefully, this plugin did not.

I’m now stuck with black text on a dark grey background.

Is the black font color hardcoded into Markdown Viewer? Can we have the option to change it to white text on a black background instead? Pretty please?

**Comment by secretGeek** [comment]
You can modify the css. Click the "?", then choose "Options" then the "Html" node - and in there you can paste in custom css.

I've got an example one I use here: https://til.secretgeek.net/notepad++/dark_theme_notepad++.html

**Comment by WandersFar** [comment]
Thank you!

I kept my CSS super simple, just one line:

`*{color:#ddd;background-color:#000}`
