### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by seanpm2001** [nea/MarkdownViewerPlusPlus#138]
***

## Issue description

_This project has not been updated in over 2 years (since 2018) and the last commit wasn't functional (it didn't pass the test) Is development ever expected to resume?_

### Markdown to reproduce

_None provided_

### Screenshot

_None provided_

### Environment

* _GitHub.com_
* _Firefox_
* _Ubuntu 20.04 Focal Fossa x64_
* _I might install the plugin if I know more about its development, as I have Notepad++ installed and emulated with WINE_

***

**Comment by stavpup** [comment]
There are so many markdown editors, I guess there is no interest in the plugin

**Comment by seanpm2001** [comment]
That is pretty understandable. Do you know the current most popular Notepad++ markdown editor that is still maintained?

**Comment by stavpup** [comment]
https://www.slant.co/topics/1852/~best-markdown-editors-for-linux
