### ISSUE TITLE
Borders around tables?

### ISSUE THREAD

**Issue by JC3** [nea/MarkdownViewerPlusPlus#146]
Hi,

Is there a way to make the viewer display borders around Markdown tables?

Thanks!

**Comment by patricktokeeffe** [comment]
[Yes](https://github.com/nea/MarkdownViewerPlusPlus/issues/24#issuecomment-366434451). Plugins > Markdownviewer++ > Options > HTML > 

```
table {
    border-collapse: collapse;
}
tr, td, th {
    border: 1px solid #AAA;
    padding: 4px;
}
```

**Comment by JC3** [comment]
Sweet, thanks!!

**Comment by patricktokeeffe** [comment]
Glad I could help! (Please remember to close if this is resolved)
