### ISSUE TITLE
appveyor yml

### ISSUE THREAD

**Issue by chcg** [nea/MarkdownViewerPlusPlus#17]
Could you please add your appveyor config as appveyor.yml to the github project so forked projectes could reuse it.

See e.g.
https://github.com/gallettube/MusicPlayer/blob/master/appveyor.yml

And maybe consider registering it at
https://npppm.bruderste.in/

for distribution via the plugin manager, also x64 is not available yet.

**Comment by nea** [comment]
Hi there

I already requested access to the plugin manager but havent received a confirmation so far.

Regarding appveyor: I just have a standard config setup in Appveyor directly. But I will create a config later on and commit it accordingly.


Best

**Comment by bruderstein** [comment]
@nea there's some issues with signup at the moment - if you can drop me a mail (my mail is on my github page) with the username you registered with, and I'll enable it.

**Comment by nea** [comment]
Hi @bruderstein 

Big thanks for getting back at me here.

I sent you a mail via my Yahoo account. The username is the same as here, so nea ^^


Thanks big time :)

**Comment by nea** [comment]
Hey @chcg 

I commited my basic appveyor.yml but nothing special, as most of the stuff is done via MSBuild script in the project file of the markdown viewer.


Cheers

**Comment by bruderstein** [comment]
@nea your account has been enabled.

**Comment by nea** [comment]
Thanks a lot @bruderstein

**Comment by nea** [comment]
Hey @chcg 

Thanks for pushing this. I added the MarkdownViewer++ to the Plugin Manager list and it should be part of the next update.


Cheers
