### ISSUE TITLE
T: Open PDF/HTML after export

### ISSUE THREAD

**Issue by philippbeckmann** [nea/MarkdownViewerPlusPlus#20]
New option for opening the exported file with the default application

**Comment by nea** [comment]
Hey Philipp

Yeah, I had similar thoughts already but haven't put a big focus on it. As I am working on some "Send to" functionality, I will see how this may fit best in the future.


Thanks for the push ^^

**Comment by nea** [comment]
Hi @philippbeckmann 

I just added two settings in the options dialog to open exported PDF and HTML files after the action completed.


Cheers
