### ISSUE TITLE
How to setup supported np++ version?

### ISSUE THREAD

**Issue by LITTOMA** [nea/MarkdownViewerPlusPlus#28]
The release 64 bit dll is work on np++ 7.3.3, however, it doesn't work if I build from source. It comes up with a message that MarkdownViewerPlusPlus.dll is not compatible with the current version of Notepad++.

**Comment by LITTOMA** [comment]
Something wrong with the UnmanagedExports. Some function symbol doesn't export.

**Comment by nea** [comment]
Hi @LITTOMA 

What build settings do you use? Any CPU does not work. You have to use x86 or x64. Also, only "Debug" works for the moment.

Also check that all paths are correct in
* https://github.com/nea/MarkdownViewerPlusPlus/blob/master/MarkdownViewerPlusPlus/MarkdownViewerPlusPlus.csproj
and
* https://github.com/nea/MarkdownViewerPlusPlus/blob/master/MarkdownViewerPlusPlus/PluginInfrastructure/DllExport/NppPlugin.DllExport.targets

The setup is not ideal but I am using exactly what is checked in here at GitHub.

Also, has everything worked out with NuGet refresh? All packages are available?


Best

**Comment by LITTOMA** [comment]
Hi, @nea 

Thanks for your answer.
I change my system language to English, then everything is OK.

**Comment by nea** [comment]
Hey

Oh.. ok. Good to know. Will have to check why. Thanks for the feedback.

Mii yeah, but my old one. Don't play any anymore... maybe the Switch will convince me in the future ^^


Cheers
