### ISSUE TITLE
local images

### ISSUE THREAD

**Issue by Alex0322** [nea/MarkdownViewerPlusPlus#30]
It cant render "\![foo]\(train.jpg)” or i miss smth?

Broken picture in preview, exported pdf, printed pdf, but shows properly if open html in web-browser.

**Comment by nea** [comment]
Hi @Alex0322 

Please check https://github.com/nea/MarkdownViewerPlusPlus/issues/23 for examples on how to load local images. You need to add the type prefix for loading for an internal selection how to grab the image.


Cheers

**Comment by Alex0322** [comment]
ok thx
