### ISSUE TITLE
line breaks within paragraph not recognized

### ISSUE THREAD

**Issue by thomasfa18** [nea/MarkdownViewerPlusPlus#42]
single carriage return in text isn't displayed in preview as a new line within paragraph, it is displayed as a continuation on the same line.

eg: the text:
this is line 1
this is line 2

gets rendered as "this is line 1 this is line 2"

**Comment by nea** [comment]
Hi @thomasfa18 

If you like to have line breaks you have to comply to the CommonMarkSpec and their definition of line breaks. Best have a look at http://spec.commonmark.org/0.27/#hard-line-breaks. There are some examples. In your case either do a double line-break or add two spaces to the end.


Cheers
