### ISSUE TITLE
Strikethrough effect missing

### ISSUE THREAD

**Issue by simopaasisalo** [nea/MarkdownViewerPlusPlus#43]
Hi,

Just noticed that I can't get the ~~strikethrough~~ effect in the extension.

Steps to replicate:
Add any string encapsulated with ~~ (for example `~~example~~`)
Expected behavior:
Encapsulated string is enhanced with the strikethrough effect
Actual behavior:
Effect is not applied, ~'s are shown in the panel

Version 0.7.1.30398, installed through Plugin Manager.

**Comment by nea** [comment]
Hey @simopaasisalo 

Strike through is currently still in specification discussion of Commonmark and therefore not included. But I will switch to a different Markdown implementation soon, which will support this.


Sorry about the confusion

**Comment by nea** [comment]
Hi @simopaasisalo 

Sorry for the long delay but I just released [0.8.0](https://github.com/nea/MarkdownViewerPlusPlus/releases/tag/0.8.0). 

With the change to Markdig strikethrough should work now via ~~.


Best
