### ISSUE TITLE
Tables don't render

### ISSUE THREAD

**Issue by javajon** [nea/MarkdownViewerPlusPlus#44]
Copy the table as noted in this tutorial and you will see it not render. Perhaps table rendering is not implemented yet.

https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet

**Comment by nea** [comment]
Hi @javajon 

Yes, it is known ^^ Please refer to https://github.com/nea/MarkdownViewerPlusPlus/issues/24 regarding the details.

I am still working con changing the backend converter to allow tables in the future :)


Cheers
