### ISSUE TITLE
PDF font for nested lists

### ISSUE THREAD

**Issue by jiggunjer** [nea/MarkdownViewerPlusPlus#46]
When I export as PDF my lists have odd glyphs: 

- tier 1 a small black dot. 
  - tier 2 a larger white circle.
    - tier 3 a black spade (card symbol).

HTML version viewed in chrome looks much better. So is there a fix for the PDF version?
 I'm on Windows 8.1.

**Comment by nea** [comment]
Hi @jiggunjer 

You can configure the bullet styles via the HTML CSS options in the configuration.

For example, you could add the custom CSS
`ul li {
   list-style-type: disc;
}

ul > li > ul > li {
    list-style-type: circle;
}`


Cheers
