### ISSUE TITLE
Plugin prevents Notepad++ starting up

### ISSUE THREAD

**Issue by twomugs** [nea/MarkdownViewerPlusPlus#52]
When the MarkdownViewerPlusPlus plug-in is enabled, NotePad++ does not start up correctly. It appears in Task Manager, but the window does not show. The problem is resolved when MarkdownViewerPlusPlus.dll is moved to the disabled subfolder. Removing all other plugins apart from MarkdownViewerPlusPlus did not fix the problem.

It may just be coincidence, but http://notepad-plus-plus.org is not accessible at the moment.

System details:
Windows 10 Pro 64-bit (1511)
Notepad++ 5.5.1 32-bit
MarkdownViewerPlusPlus 0.7.1

**Comment by twomugs** [comment]
Sorry, typo in the Notepad++ version. Should read 7.5.1

**Comment by nea** [comment]
Ok @twomugs, that is something different ^^

**Comment by twomugs** [comment]
I've re enabled the MarkdownViewerPlusPlus plug-in, and notepad++ is starting up ok again now.

I don't know if it was Windows having a bad day, or the npp web site being down, or somthing else.

I guess you can probably close this now.

**Comment by nea** [comment]
Oh, ok. Good to know. Thanks for retry and report :)
