### ISSUE TITLE
Changing the "bullet" on  Nested List 

### ISSUE THREAD

**Issue by settonfarms** [nea/MarkdownViewerPlusPlus#58]
Hello,

Thank you for making the  plugin. 

When I have nested list this indented looks like this.  I do not like the spade icon used. Is there a way to change this? Also I've noticed other markup views, dilllinger, markdownlive, do not use them. 

![example image](https://user-images.githubusercontent.com/35269305/35005601-c9ad27de-faa8-11e7-8ad2-29d7de692861.PNG)

**Comment by nea** [comment]
Hey @settonfarms 

Please checkout #29 to get an idea how to change the styling via custom CSS.

My very simple CSS looks like this:
`ul li {
   list-style-type: disc;
}

ul > li > ul > li {
    list-style-type: circle;
}`


Best
