### ISSUE TITLE
Mathematics equations support

### ISSUE THREAD

**Issue by SpinoPi** [nea/MarkdownViewerPlusPlus#59]
Hi nea,
  Thank you so much for your excellent work on this plugin. I have a little question about its usage, how could I write mathematics equations?  "$$" seems not work in MarkdowViewerPP. Thank you!

**Comment by nea** [comment]
Hi @SpinoPi 

I just released a new version [0.8.0](https://github.com/nea/MarkdownViewerPlusPlus/releases/tag/0.8.0). 

I changed the Markdown renderer to Markdig which supports basic math equations like https://github.com/lunet-io/markdig/blob/master/src/Markdig.Tests/Specs/MathSpecs.md.

I hope this helps.


Cheers

**Comment by SpinoPi** [comment]
Thank you very much for this great work! @nea

**Comment by RoyiAvital** [comment]
If I remember correctly this holds for the HTML output yet the view pane doesn't display Math, right?
