### ISSUE TITLE
not whole file rendered

### ISSUE THREAD

**Issue by vrz** [nea/MarkdownViewerPlusPlus#60]
not whole preview of markdown file visible

**Comment by nea** [comment]
Hi @vrz 

Could you give me an example markdown you want to view or a screenshot?


Thanks a lot

**Comment by vrz** [comment]
Notepad++ ver. 7.5.4
Windows 7 x64
MarkdownViewer++ ver. 0.8.0.19087

Среда, 21 февраля 2018, 13:29 +03:00 от Savas Ziplies <notifications@github.com>:

**Comment by nea** [comment]
Hey @vrz 

Thanks for that. I was looking for what is not rendered completely? What does your text look like in Npp?


Thanks a lot

**Comment by vrz** [comment]
I'm not understanding your questions.
I've sent you file 'markdown.md' &  screenshot.
On screenshot you can see that viewer stopped on string 'Incomplete t'.
It is incompleted line #299 in original file, which totally has 797 lines.




Среда, 21 февраля 2018, 15:15 +03:00 от Savas Ziplies <notifications@github.com>:
>Hey  @vrz
>Thanks for that. I was looking for what is not rendered completely? What does your text look like in Npp?
>Thanks a lot
>—
>You are receiving this because you were mentioned.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


---
Приглашаем пообщаться на www.talk.ru

**Comment by nea** [comment]
Hey @vrz 

This is the Github Forum and no email communication, so I do not get your attachments, sorry.

You would have to add them directly to the Github thread at https://github.com/nea/MarkdownViewerPlusPlus/issues/60 and not via mail reply.


Thanks

**Comment by vrz** [comment]
[mdNpp.zip](https://github.com/nea/MarkdownViewerPlusPlus/files/1746617/mdNpp.zip)

**Comment by einaruk** [comment]
I am also not able to render tasklist as in below example;

- [x] this is a complete item
- [ ] this is an incomplete item

**Comment by vrz** [comment]
problem not just with tasklist
![mdnpp_bug](https://user-images.githubusercontent.com/8409104/36528497-5e4c0222-17c6-11e8-95b2-baa272741467.png)

**Comment by nea** [comment]
Hey @vrz, @einaruk 

Sorry about the hold up but we are mixing a lot of things here and I have to sort that out first and need to really know every single issue.

Regarding task lists: The output to HTML is correct, so if you export it you would have the correct result. But the currently used HTMLRenderer does not support <input> fields and therefore these are not rendered. I am thinking of adding additional support for the IE View as a fallback, but have to think about that first.

Regarding your second problem: What exactly is missing here? What you selected looks correct.


Thanks

**Comment by vrz** [comment]
File preview stopped at line 168. File has 1232 lines.
version 0.7.1 shows all correctly

**Comment by vrz** [comment]
version 0.7.1
![mdnpp_good](https://user-images.githubusercontent.com/8409104/36529048-2b71080a-17c8-11e8-9541-49022479737a.png)

**Comment by nea** [comment]
Hey @vrz 

Thanks a lot for this use case. I don't know if I forgot something after the long time getting back into the project but it stops after 10000 characters... don't know why atm but will look into it.


Thanks a lot

**Comment by nea** [comment]
Hi @vrz 

Found the bug. Unfortunately an old bug I brought back in after this long time ^^'

Really sorry about that. Will be fixed with version 0.8.1 very soon.


Thanks big times for your helpful feedback
