### ISSUE TITLE
&nbsp; does not work

### ISSUE THREAD

**Issue by einaruk** [nea/MarkdownViewerPlusPlus#61]
## Issue description
I need to put extra spaces between/after the words. But could not manage. I do not know if it is supported or not. 

### Markdown to reproduce
I tried putting \&nbsp; but it did not work.
```markdown
I need space after this word &nbsp; &nbsp; &nbsp; before this word. 
```

Even I see putting \&nbsp; ugly in text. Is there a better way?

### Environment
* Notepad++ 7.5.4 x86
* MarkdownViewer++ 0.8
* Windows  7

**Comment by nea** [comment]
Hi @einaruk 

This is not possible. But what you can do are two things I can think up right now:
* "I need space after this word ` ` ` ` ` ` ` ` before this word. " <- Space it with two ` and a space between.
* Indent the line by four whitespaces to make it a code/pre block

I hope this helps.


Best

**Comment by einaruk** [comment]
Hi @nea,
   Thanks for the suggestion. I Tried to put multiple \`  \`  but it works only for creating +1 additional space, which means max space length between the words is limited to 2 spaces.

see below please
```markdown
text before multiples spaces ` ` ` ` ` ` ` ` ` ` text after multiple spaces
```
renders to;
- text before multiples spaces ` ` ` ` text after multiple spaces
whereas github renders correctly to below;
- text before multiples spaces ` ` ` ` ` ` ` ` ` ` text after multiple spaces

Actuall the reason I want to create multiples spaces is to enhance the look of the tables the plugin renders. Currently the rendered tables seems to be quite dense and mixed when there is much text.  

An extra question; do you plan to bring borders to table?

**Comment by nea** [comment]
Hey @einaruk 

Weird, for me the spaces grow fine. Your example really adds all the spaces for me.

I will not add borders to tables as this is not markdown related but styling. For that you can use the "Options" dialog and add table CSS styling. You can checkout #24 for an example.

Regarding tables in general, you can checkout 
* https://github.com/lunet-io/markdig/blob/master/src/Markdig.Tests/Specs/PipeTableSpecs.md and
* https://github.com/lunet-io/markdig/blob/master/src/Markdig.Tests/Specs/GridTableSpecs.md

for possibilities.


Best

**Comment by einaruk** [comment]
Hi @nea ,
   Thanks a lot. That CSS trick helped a lot.
Waiting for new features and more compliance with github style markdown :).


Regards

**Comment by nea** [comment]
@einaruk for more Markdown features push the https://github.com/lunet-io/markdig guys ^^'
