### ISSUE TITLE
9612 utf-8 chars limit

### ISSUE THREAD

**Issue by andrzejQ** [nea/MarkdownViewerPlusPlus#62]
## Issue description
_For text file larger then 9612 chars MV++ stops working_

### Environment
* Notepad++ _7.5.4 (x86)_
* MarkdownViewer++ _0.8_
* Windows _10 (x64)_

**Comment by nea** [comment]
Hi @andrzejQ 

Could you please verify with the newest release 0.8.1 which I just published today
https://github.com/nea/MarkdownViewerPlusPlus/releases/tag/0.8.1

There was an unfortunate bug that sounds like it.


Thanks

**Comment by andrzejQ** [comment]
Yes - works great.

**Comment by nea** [comment]
Awesome.

Thanks for retesting @andrzejQ
