### ISSUE TITLE
Scroll Sync

### ISSUE THREAD

**Issue by einaruk** [nea/MarkdownViewerPlusPlus#66]
## Issue description
I would like if scrolling the scrollbar in any of the edit or view tabs should sync (scroll down or up) the other tab

### Markdown to reproduce
1) Paste a long text in edit. The page will render in MDVPP render page
2) Scroll-down the text edit page scrollbar. 

3) Expectation: Scroll in edit should also scroll the page in render window (in sync)

### Screenshot
_If available_

### Environment
* Notepad++  7.5.4 32 bit
* MarkdownViewer++ 0.8.1
* Windows 7

**Comment by nea** [comment]
Hi @einaruk 

One question regarding this: Did you enable synchronized scrolling? Editor to Render View scrolling is already implemented.


Thanks

**Comment by einaruk** [comment]
Hi @nea 
It is my bad not to check well enough. Now I found the option, enabled it and it works. 
Thanks.

**Comment by nea** [comment]
Awesome! ^^
