### ISSUE TITLE
"::" vanishing in doc inner hyperlinks (tcl)

### ISSUE THREAD

**Issue by stanpetit** [nea/MarkdownViewerPlusPlus#67]
## Issue description
Hi ! Thanks for the tables !
In the following *tcl* extract :  `[ddt::GetSource]` is expected to be a hyperlink to `### Proc: ddt::GetSource` just below, but the `::` are vanishing, devoured by some parsing rule between the link's hooks  ...  

The weird stuff is that : 
+   the `::` and links are vanishing in the MDVPP's display panel
+   the exported html displays `::` again but inside the `[hooked::stuff]`, and they are not produced as a html link

I guess other languages than *tcl* (docs) are affected too.

Best, Stan
### Markdown to reproduce
```
****
### Proc: ddt::GetSourceId

Returns the source identifier for a file. The source identifier is an integer.

#### See Also

[ddt::GetSource]

****
### Proc: ddt::GetSource

```

### Screenshot
_If available_

### Environment
* Notepad++ 7.5.1 (x86)
* MarkdownViewer++ 0.8.0 19087
* Windows 7(x64)

**Comment by nea** [comment]
Hi @stanpetit 

I hope I got your problem right, but complex anchors are not part of the CommonMark specification http://spec.commonmark.org/0.28/#links.

There is an ongoing discussion about this in the forums https://talk.commonmark.org/t/anchors-in-markdown/247/28.

Simple anchors can be done, for example
`[link](#Link)`
http://spec.commonmark.org/0.28/#example-472

But there are limitations such as
`The destination cannot contain spaces or line breaks, even if enclosed in pointy brackets`
http://spec.commonmark.org/0.28/#example-463


Best

**Comment by stanpetit** [comment]
Hi @Savas

Are you on the deck night and day ? :) Thanks for the prompt reply.

As far as can read spec.commonmark
<http://spec.commonmark.org/0.28/#example-463> and more, the ":" char is
not an "unsafe" or "reserved" char, thus should be preserved in the link's
string.

Let me describe again :

   - the "::" are vanishing from the string "[my::link]" in the MDVPP's
   preview panel and links are not produced in preview panel.
   - the exported html displays "::" in the string again but inside the
   [hooked::stuff] : they are not produced as a link in the html.
   - though, the difference of display behavior in these 2 steps seem to be
   an inconstancy ...

Neither link-text <http://spec.commonmark.org/0.28/#link-text> or
link-destination <http://spec.commonmark.org/0.28/#link-destination> or
link-title <http://spec.commonmark.org/0.28/#link-title> describe ":" as a
forbidden char in any part of the hyperlinks mechanism.

This pattern is common to many *C *related languages : which dev would
shoot a bullet in it's foot with such a restriction on the syntax ?

IMH observations, it should just be treated as a regular ASCII char in
hyperlinks, that are only text contents of an html tag, and everyone will
be happy :)

Don't feel obliged to answer to that note !

Best, Stan.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Garanti
sans virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2018-03-06 15:00 GMT+01:00 Savas Ziplies <notifications@github.com>:

**Comment by stanpetit** [comment]
I've just tried  :

### my::link
[my::link](my::link)

on dingus <http://spec.commonmark.org/dingus/>, and it doesn't reject it !


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Garanti
sans virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2018-03-06 15:00 GMT+01:00 Savas Ziplies <notifications@github.com>:

**Comment by stanpetit** [comment]
Note that the previous version that I was using (same NPP) was producing
links containing "::" with no problem.
I have updated yesterday.
I couldn't tell which version precisely, less than 6 month old is sure ...

I would consider this as a tiny bug.

Best, Stan

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Garanti
sans virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2018-03-06 15:00 GMT+01:00 Savas Ziplies <notifications@github.com>:

**Comment by nea** [comment]
Hi @stanpetit 

`### my::link
[my::link](my::link)`

works well with the plugin in NPP, too.

What doesn't work is a space. It is not the colon.


Best

**Comment by stanpetit** [comment]
Yep sir ! I've got it, thanks !

I don't understand why the redundancy is needed in the case of implicit
inner links.

There must be a good reason ...
Thanks again !

Best, Stan

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Garanti
sans virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2018-03-06 16:28 GMT+01:00 Savas Ziplies <notifications@github.com>:

**Comment by nea** [comment]
Hey

Sorry, dont really know. Judt using the spec implementation. 


Sorry
