### ISSUE TITLE
Notepad++ crashes when editing *.md in realtime 

### ISSUE THREAD

**Issue by dvdvideo1234** [nea/MarkdownViewerPlusPlus#69]
## Issue description

1. Download [this][my_readme]
2. Replace all the three backticked tokens with ```\n```
3. Click the MD icon in NPP
4. Strech the window on the two extended monitors \
and the NPP docking to be on the left monitor and \
MD to be on the half of the right monitor surface
5. Type something reasonably fast like 3-4 letters a second

### Markdown to reproduce
I think [this][my_readme] is pretty self explanatory

### Screenshot
![code_editor](https://user-images.githubusercontent.com/9112662/38085618-dfc8fef0-3359-11e8-9fa6-efc8db94b52e.JPG)

### Environment
* Notepad++ _7.5.6 x86_ **(From the [website](https://notepad-plus-plus.org/download/v7.5.6.html))**
* MarkdownViewer++ _0.8.0.19087_ **(PluginManager)**
* Windows _7 x64_

I have to add more stuff to this file so this is kinda blocking for me, though am not a rush to fix it.

[my_readme]: https://raw.githubusercontent.com/dvdvideo1234/TrackAssemblyTool/master/readme.md

**Comment by nea** [comment]
Hi @dvdvideo1234 

Have you tried updating the plugin to release 0.8.1 https://github.com/nea/MarkdownViewerPlusPlus/releases/tag/0.8.1?

What do you mean by: "Replace all the three backticked tokens with \n"

And regarding the fast typing: Yeah, I know. At the moment every change triggers a redraw. In your case a redraw of a pretty big document with large images. I am still working on adding a delay to this to counter quick typing in one of the next releases. Another thing would be to have images disabled. Never thought about that.


Thanks

**Comment by dvdvideo1234** [comment]
> Have you tried updating the plugin to release 0.8.1 
So far I did not, the plugin manager shows that it has no updates pending

> What do you mean by: "Replace all the three backticked tokens with \n"
Open the file via Npp:
1. Select ``` ``` ```
2. Ctrl-R
3. Click the ```Extended``` checkbox on the search options
4. Click ```Replace all```

So far crashes wen it is maximized on the left and right monitor. When it is not maximized, it is rather more sturdy when processing the MD

**Comment by nea** [comment]
Hey @dvdvideo1234 

Ok, does not crash for me. Really seems to be the load in redrawing. Thanks for the big example document, so I can check with this use-case furthermore to identify what to do.

Until then... sorry ^^'

**Comment by dvdvideo1234** [comment]
Np. ;) The document is not critical for me, but some people are having trouble reading it, because I gotta put quite a lot of stuff in there to explain everything in my code, so some suggested that I should at least put `#` headers to break it apart. Apparently that way is far more stable when editing in NPP. \
Is it going to be better if the re-drawing is like synced in half of a second for example and triggered [**IFF**](https://en.wikipedia.org/wiki/If_and_only_if) a flag is present for a key _**is pressed**_ ?

**Comment by dvdvideo1234** [comment]
Here is the [error](https://github.com/nea/MarkdownViewerPlusPlus/files/1859985/npp_app_error.txt) and the [information](https://github.com/nea/MarkdownViewerPlusPlus/files/1859984/npp_app_error_info.txt) about it extracted from the windows event viewer. I know it's not much, but it might help ;)

**Comment by dvdvideo1234** [comment]
Hello,

I found a workaround for my problem, which I used to update the [document](https://github.com/dvdvideo1234/TrackAssemblyTool/blob/master/readme.md). I switched off the markdown viewer, made my edits and toggled a preview. I thought you should know ;)

Cheers !

**Comment by dvdvideo1234** [comment]
I've relocated the markdown readme to the github Wiki. Problem solved :smile_cat:
