### ISSUE TITLE
"This ANSI plugin is not compatible with your Unicode Notepad++." error

### ISSUE THREAD

**Issue by monoblaine** [nea/MarkdownViewerPlusPlus#70]
## Issue description
I've tried to run Notepad++ using a a custom-built `MarkdownViewerPlusPlus.dll` but I get the following error:

```
This ANSI plugin is not compatible with your Unicode Notepad++.

MarkdownViewerPlusPlus.dll is not compatible with the current version of Notepad++.
```

So far I've tried the following branches:

* `master`: I cannot even get to build the solution
* `0.8.0` and `0.8.1`: The solution successfully builds, the file `MarkdownViewerPlusPlus.dll` automatically gets copied into `C:\Program Files (x86)\Notepad++\plugins\` but I get the error above.

### Other info

* I'm using the preview version of VS 2017
* NuGet package restore for HtmlRenderer* packages failed, so I've cloned your fork, built it, and added the output dlls as a reference.

Also, I guess the active solution platform needs to be "Any CPU" because if I choose the other options (either x86 or x64) I get the following error:

```
MarkdownViewerPlusPlus.il(421393) : warning : Method has no body, 'ret' emitted
MarkdownViewerPlusPlus.il(421398) : warning : Method has no body, 'ret' emitted
MarkdownViewerPlusPlus.il(421407) : warning : Method has no body, 'ret' emitted
```

### Environment
* Notepad++ _7.5.4 (x86)_
* MarkdownViewer++ _0.8.x_
* Windows _10 (x64)_

**Comment by monoblaine** [comment]
## More info

I managed to get it work for the `0.8.1` branch with the following steps:

* It appears I have to use the `PDFsharp.1.50.4790-beta5a` branch of `HTML-Renderer`.
* I built `HTML-Renderer` after I've followed these steps (for all 3 projects):
    * Change the target framework to `.NET Framework 4 Client Profile` (I'm not really sure if this is really a necessarry step)
    * Make sure active solution configuration is `Release` and `x86`
* Add the output dlls of `HTML-Renderer` as references (The `HTML-Renderer` packages in `packages.config` cannot be found in NuGet package repo)
* Add NuGet package `Microsoft.Office.Interop.Outlook` to the project
* Change active solution configuration to `Debug` and `x86` (`Release` mode won't work)
* Build the project

The only problem that remains is that I cannot get it work if I build the project using `Release` mode. Notepad++ launches with no alert, warning or anything. But the markdown viewer won't show up.

**Comment by nea** [comment]
Hi @monoblaine 

The reason you cannot build it is because I have a custom PDFSharp Version in my personal, local NuGet that wasn't available when I was building it, because I updated some dependencies I required on all ends in HTMLRenderer etc. As soon as PDFSharp is updated, too, I will switch back.

Release build does not work. AnyCPU may not be selected. x86 or x64.


Best

**Comment by DimitrijeK** [comment]
Hi @nea & @monoblaine, 

I recently figure it out so I though it would be good to share how I did it. I used VS2017 and the newest verision of NotePad++. After adding all missing packages and downgrading PdfSharp package to 1.50.4000-beta3b, I was able to succesfully build the solution. Before you build make sure that you have Debug and x86 selected. After building VS2017 will generate .dll file in the bin folder of your project.

After I tried to copy .dll file to plugins folder of NP++ I was getting the following error:

    -The ANSI plugin is not compatible with your Unicode Notepad++
    -MarkDownViewerPlusPlus.dll is not compatible with the current version of your Notepad++
Then I got around this by installing Plugin Manager for NP++ (PluginManager_v1.4.11_UNI.zip)

    -https://github.com/bruderstein/nppPluginManager/releases

Then I installed MarkDownViewerPlusPlus thru plugin manager, and then copied the .dll file (Debug, x86) from the previous build and replaced the one installed thru plugin manager. After that I was able to open Notepad++ with no errors and MarkDown plugin was working!!!

Thank you for your time!!!!!
Hope somebody finds this helpful!

**Comment by monoblaine** [comment]
Hi @DimitrijeK,

When you build the project, `MarkDownViewerPlusPlus.dll` is supposed to get automatically copied to the plugins folder of Notepad++. There's actually a build task for that in `MarkdownViewerPlusPlus.csproj`:

```
<Copy Condition="Exists('C:\Program Files (x86)\Notepad++\plugins\') AND '$(PlatformTarget)'=='x86'" SourceFiles="$(TargetPath)" DestinationFolder="C:\Program Files (x86)\Notepad++\plugins\" ContinueOnError="false" />
```

That was probably not happening because you didn't have the Plugin Manager installed. Now that you've installed it, things should work that way. (Just make sure you close Notepad++ before you build the project.)

**Comment by DimitrijeK** [comment]
Hi @monoblaine,

Yeah I know it is supposed to copy the dll file after you build it, but I was at work and the pc I am working won't give me premission to copy files thru that build process, so I just commented out that copy condition. But I get what you are trying to say.

Thank you!

**Comment by bhu1st** [comment]
> I managed to get it work for the `0.8.1` branch with the following steps:

@monoblaine I was able to build version 0.8.1 in Visual Studio 2022 for x86 using PDFSharp `1.50.4000-beta3b` as suggested by @DimitrijeK 

Other packages:
HtmlRenderer.Core -> 1.5.1-beta1 
HtmlRenderer.PdfSharp -> 1.5.1-beta1
HtmlRenderer.WinForms -> 1.5.1-beta1

When copying the plugin files to Notepad++ 8.6.8 (x86) plugins folder I still get the same error "This ANSI plugin is not compatible with your Unicode Notepad++" 

https://github.com/kbilsted/NotepadPlusPlusPluginPack.Net/issues/52
This mentions running "makerelease.ps1" for NotepadPlusPlusPluginPack.Net：0.94.00 but it seems like all the files in v0.8.1 are already UTF-8.

Also, on this Npp community thread, "[C# Plugin Development and Error: This ANSI plugin is not compatible with your Unicode Notepad++](https://community.notepad-plus-plus.org/topic/25334/c-plugin-development-and-error-this-ansi-plugin-is-not-compatible-with-your-unicode-notepad)"  Paul Baker suggested changing the post-build tasks but I am lot at this.

Has anyone tried to build it recently? Any luck?
