### ISSUE TITLE
Images doesn't show up

### ISSUE THREAD

**Issue by bongo1234** [nea/MarkdownViewerPlusPlus#73]
## Issue description
Images doesn't show up with:

### Markdown to reproduce
```
![test-image](image.png)
```
but it works with
```
![test-image](C:/image.png)
```
Image and File has the same path. But its not `C:/`
### Environment
* Notepad++ _7.5.6 (x64)_
* MarkdownViewer++ _0.8.1_
* Windows 10 _(x64)_

**Comment by nea** [comment]
Hi @bongo1234 

For now please refer to https://github.com/nea/MarkdownViewerPlusPlus/issues/23#issuecomment-287190881 how the file paths have to be added.

Will be changed in the future.


Best

**Comment by arturomoncadatorres** [comment]
If anyone else ends up here looking for a solution, this [has been fixed](https://github.com/nea/MarkdownViewerPlusPlus/issues/134) in MarkdownViewer++ 0.8.3. For some reason, [this release isn't officially listed](https://github.com/nea/MarkdownViewerPlusPlus/releases), but you can [download it here](https://github.com/user-attachments/files/15855993/MarkdownViewerPlusPlus-0.8.3-x64.zip). 

To install it, just copy and paste the files in the corresponding MarkdownViewer++ plugins directory (e.g., `C:\Program Files\Notepad++\plugins\MarkdownViewerPlusPlus`)

**Comment by simonnewell** [comment]
> If anyone else ends up here looking for a solution, this [has been fixed](https://github.com/nea/MarkdownViewerPlusPlus/issues/134) in MarkdownViewer++ 0.8.3. For some reason, [this release isn't officially listed](https://github.com/nea/MarkdownViewerPlusPlus/releases), but you can [download it here](https://github.com/user-attachments/files/15855993/MarkdownViewerPlusPlus-0.8.3-x64.zip).
> 
> To install it, just copy and paste the files in the corresponding MarkdownViewer++ plugins directory (e.g., `C:\Program Files\Notepad++\plugins\MarkdownViewerPlusPlus`)

This is a great tip. Thank you. To add to this.  I needed to download & install the latest version of Notepad++ for this to work.

**Comment by DavidBruchmann** [comment]
downloading a zip file without access to the source before the download, i. e. in a fork, looks hacky -- even from github.
So linking to a fork would be the correct procedure.
