### ISSUE TITLE
Mongodb issues econnrefused with a clean repo

### ISSUE THREAD

**Issue by NinthDesertDude** [nea/MarkdownViewerPlusPlus#75]
## Issue description
I'm following the [associated tutorial](https://thinkster.io/tutorials/node-json-api/initializing-a-starter-node-project) and downloaded the seed branch. I ran npm install. I tried node app.js and received this error:

> Listening on port 3000
> 
> mypath\node_modules\mongodb\lib\server.js:242
>         process.nextTick(function() { throw err; })
>                                       ^
> Error: connect ECONNREFUSED 127.0.0.1:27017
>     at Object._errnoException (util.js:1022:11)
>     at _exceptionWithHostPort (util.js:1044:20)
>     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
> PS mypath>

It doesn't work on other random ports either, like 1885. Is there a firewall setting or something? Also, I read a post suggesting that mongoose is a server. If I'm expected to download and run it as a server, please, *please* cover these things in the initial tutorial; there are too many node packages to assume familiarity with any particular set.

## Environment
* Windows 10, 64-bit

**Comment by nea** [comment]
HI @JoshuaLamusga 

Did you get on the wrong repository maybe? Because there is no MongoDB in the MarkdownViewer++ ^^

Just guessing: On the top its listening to port 3000, below connection is being established to 27017. Maybe somethings mismatched.


Cheers

**Comment by NinthDesertDude** [comment]
I'm totally on the wrong repository. Sorry! (...but thanks for the tip.)
