### ISSUE TITLE
Can't validate integrity

### ISSUE THREAD

**Issue by okonomiyaki3000** [nea/MarkdownViewerPlusPlus#77]
## Issue description
I'm trying to install using Plugin Manager. Everything goes well enough until the end when Plugin Manager says "It has not been possible to validate the intergrity of 'MarkdownViewerPlusPlus.dll' needed to install or update a plugin." 

It then gives me the option to install anyway but it recommends not installing. 

### Environment
* Notepad++ _7.5.6 (x64)_
* MarkdownViewer++ _0.8.2_
* Windows _7 (x64)_

**Comment by nea** [comment]
Hi @okonomiyaki3000 

Could you do me a favor and post it at https://github.com/bruderstein/npp-plugins-x64. 

I double checked the *.dll hash now and everything seems correct. I wouldn't know why it says invalidate then.


Sorry

**Comment by chcg** [comment]
@nea Changed 86AD1BC5DB7B25264B240B5F2B924169 -> 86ad1bc5db7b25264b240b5f2b924169 to fix this issue with the MD5 sum. Fix is currently just available with the development plugin list. The transfer to the normal list will happen automatically within the next days.

**Comment by nea** [comment]
@chcg Ahhhhhhhhh.... thanks for the hint ^^'

Will take care about next time.

**Comment by okonomiyaki3000** [comment]
Wouldn't it just be better for everyone if such codes were case-insensitive though?

**Comment by chcg** [comment]
See https://stackoverflow.com/questions/45153520/are-md5-hashes-always-either-capital-or-lowercase, currently PM seems to accept just lowercase. Similar issue could be observed e.g. with https://github.com/pivotal-cf/pivnet-resource/issues/62 and https://github.com/TeamWin/Team-Win-Recovery-Project/issues/912

**Comment by okonomiyaki3000** [comment]
Sure, sure, I know this kind of thing is always up to the receiver of the hash to handle but it seems like a no-brainer to make it handle either upper or lower case. Essentially, a hex string is a number. It's just in base-16 instead of base-10 so we use some letters for the extra digits that our base-10 system lacks. There's no issue of case when dealing with base-10 numbers so there shouldn't be one when dealing with base-16. And it's literally 1 line of code for any application to normalize any hash it receives to be either all upper or all lower. So it's totally silly to me that any application is picky about such a thing.
