### ISSUE TITLE
List items are on new line from bullet point

### ISSUE THREAD

**Issue by robertlarkins** [nea/MarkdownViewerPlusPlus#87]
## Issue description
Using a hyphen for item on the top level list adds a new line between the bullet point and the text.

### Markdown to reproduce
```
 - A broken bullet point
   - A
   - Working
   - sub-list
```

### Screenshot
![image](https://user-images.githubusercontent.com/14414215/42974558-e48c0ca6-8c0b-11e8-92c7-423c2ff1ca0d.png)

### Environment
* Notepad++ _7.5.7 x86_
* MarkdownViewer++ _0.8.2.25525_
* Windows _10 x64_

**Comment by nea** [comment]
Hey @robertlarkins 

I tried with your example but for me all looks good. 
![image](https://user-images.githubusercontent.com/392035/42986396-ac12fb48-8bf5-11e8-9c29-59c0e12c2a93.png)

Could you enable "Show all characters" to see if there is something else?


Thanks

**Comment by robertlarkins** [comment]
Sorry, it seems I gave an incomplete example, if I go

```
 - One
   - another
   - point
   
 - Two
```

does it for me. In fact, the minimum test case is

```
 - one

 - two
```

![image](https://user-images.githubusercontent.com/14414215/43002873-7ba8a15e-8c7e-11e8-81d5-3809f4bc18aa.png)

**Comment by nea** [comment]
HI @robertlarkins 

Please refer to #86. This leads to a loose list.


Sorry
