### ISSUE TITLE
Error : accentuated characters not supported

### ISSUE THREAD

**Issue by PascalSartoretti** [nea/MarkdownViewerPlusPlus#88]
## Issue description
Accentuated characters in the "source" window are rendered as garbage in the "preview" window

### Markdown to reproduce
Source : "Texte accentué" => The "é" becomes a black lozenge with a question mark within

### Environment
* Notepad++ 7.3.3
* MarkdownViewer++ 0.8.2
* Windows 7 x64

**Comment by nea** [comment]
Hey @PascalSartoretti 

Could you please check what encoding is set in Notepad++ and on your system? Because for me it looks fine:

![image](https://user-images.githubusercontent.com/392035/43306056-27ea8766-917a-11e8-9081-b1258f5415e4.png)


Thanks

**Comment by PascalSartoretti** [comment]
Thanks, it works by explicitly encoding in UTF-8 (which is not desired) or in ISO-8859-1. It is a very acceptable workaround.
