### ISSUE TITLE
empty line in list

### ISSUE THREAD

**Issue by hjuergens** [nea/MarkdownViewerPlusPlus#93]
## Issue description
When a list contains one or more empty lines, all item entries of this list will move the text one line below. 

This happens when ever you hit return for a new item.

### Markdown to reproduce
```
  * first
  
  * second
```

### Environment
* Notepad++ v7.5.8   (64-bit)
* Build time : Jul 23 2018 - 02:06:36
* MarkdownViewer++ 0.8.2.25564
* Plugins : ComparePlugin.dll MarkdownViewerPlusPlus.dll NPPJSONViewer-x64.dll PluginManager.dll XMLTools.dll DSpellCheck.dll mimeTools.dll NppConverter.dll 
* OS : Windows 10 (64-bit)

**Comment by nea** [comment]
Hi @hjuergens 

Please refer to #86. This leads to a loose list.

Sorry
