### ISSUE TITLE
Flow issues with bulleted lists when followed by indented paragraph

### ISSUE THREAD

**Issue by thisIsMikeKane** [nea/MarkdownViewerPlusPlus#95]
## Issue description
A bulleted list followed by an indented paragraph should produce just that, with each bulleted item on the same line as the bullet. Instead, a each bulleted item incorrectly ends up on the line below. 

### Markdown to reproduce
```
* Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. 
* Sit amet consectetur adipiscing elit pellentesque. 
* Egestas sed tempus urna et pharetra pharetra massa massa. 

    Quis vel eros donec ac odio. 
```

Should produce 

* Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. 
* Sit amet consectetur adipiscing elit pellentesque. 
* Egestas sed tempus urna et pharetra pharetra massa massa. 

    Quis vel eros donec ac odio. 

### Screenshot
Instead it produces each bulleted item incorrectly ends up on the line below. 

![image](https://user-images.githubusercontent.com/997703/46237094-70ad3680-c350-11e8-9b6d-3ef4d9706d51.png)

### Environment
* Notepad++ 7.5.8 (x86/x64)
* MarkdownViewer++ 0.8.2.25525
* Windows 10 x64

**Comment by nea** [comment]
Hi @thisIsMikeKane 

Please refer to #86. This leads to a loose list.


Sorry
