### ISSUE TITLE
The relative path image cannot be displayed.

### ISSUE THREAD

**Issue by lfork** [nea/MarkdownViewerPlusPlus#97]
## Issue description
The relative path image cannot be displayed in this plugin, but can be displayed in other program.

### Markdown to reproduce
```
  <img src=".\1.jpg" width="400px" />
```
 

### Screenshot
<img src="https://lh6.googleusercontent.com/_WdwuZbuYuGJ0Ve0fj0Dn_7AUo7MOcF51aaH9E5jvti6jEiLTkhZzSGn3swTz5bVwUhf_IJsyjG6W5tGw64=w1920-h942-rw" width="400px" />

### Environment
* Notepad++ _7.5.9 x86 
* MarkdownViewer++ _0.8.2.25525
* Windows 10  x64

**Comment by nea** [comment]
Hi @lfork 

Please refer to #50 for now.


Thanks
